### ISSUE TITLE
Help on how to keep links when converted to rst 

### ISSUE THREAD

**Issue by sistia01** [CrossNox/m2r#50]
Hello!

I was wondering if there is any way to keep links that were created in an md file to the rst file. In my example I have a "Details" section in which there are links to another source (image_flop) and when these files are converted from md --> rst files the weblink breaks and the output is this: 

![Screen Shot 2022-07-14 at 4 05 17 PM](https://user-images.githubusercontent.com/59894711/179073600-02452e83-a365-448f-bd9a-69e2f9556fa1.png)

I was wondering if there is any way to keep these links from breaking and "transfer" them as I convert my md files to rst files?

[Desired outcome](http://giottosuite.com/reference/createGiottoImage.html): 

![Screen Shot 2022-07-14 at 4 05 42 PM](https://user-images.githubusercontent.com/59894711/179073653-0f360cd3-bd0b-43c6-ac1d-f1e2ab4c1522.png)

Here is my repo: https://github.com/sistia01/Giotto/tree/suite/docs

Here is an example: https://github.com/sistia01/Giotto/blob/suite/docs/source/subsections/md_rst/createGiottoImage.rst

**Comment by CrossNox** [comment]
I think this issue is the same as https://github.com/CrossNox/m2r2/issues/37, right?
